### ISSUE TITLE
[Feature Request] Verbosity Option for Command

### ISSUE THREAD

**Issue by breadgrocery** [tomwis/CommitLint.Net#6]
It would be great if there was an option to configure the verbosity level for `commit-lint` command. 

Like this below or something else:
```
--verbosity : Display this amount of information [OFF, FATAL, ERROR, WARN, INFO, VERBOSE, TRACE] (default: INFO).
```

Most of the time, developers are only interested in information related to errors or warnings when the linting fails.

Another issue is that the **stacktrace** is also printed when an error occurs.

**Comment by tomwis** [comment]
Hey, for now I fixed the issue with printing stack traces, but the requested feature is something I can look into soon as well.

**Comment by breadgrocery** [comment]
Stack traces are indeed not printed anymore.
Looking forward to further progress.

**Comment by breadgrocery** [comment]
You may also include an  extenal link in the linting result to expalin what is **conventional commit format**. 
```
For more information, please visit https://www.conventionalcommits.org.
```

**Comment by breadgrocery** [comment]
It works! Thank you!
